var strings = [
  'Esther says she will stay with Sara till July',
  'At the pool we read this:',
  'Lifeguard Here Until Four',
  'The manager ran this ad:',
  'HIGH QUALITY PAPER FOR LESS',
  'do you understand it',
  'ALL SALES ARE FINAL',
  'Does she realize what her FINE JEWELRY is worth',
  'Order it now. Order it now. Order it now. Order it.',
  'Sit up straight',
  'You should know',
  'quiet, lazy, joyful trips',
  'The vast number of people like to buy big bargains',
  'To be, or not to be: that is the question',
  'memorizing the motions',
  'merely having a mental image',
  'invest some time and effort',
  'next October',
  'coming home from Mexico in March',
  'the tax returns',
  'the box factory',
  'packed with explosives',
  'an expert in explosives',
  'fight the fire',
  'no injuries',
  'Sixty thousand dollars',
  'the houses on both sides',
  'The quick brown fox jumped over the lazy dogs',
  'a beginner--with ambition',
  'for CARE OF',
  'the DIAGONAL is SLANT',
  'first-class tickets',
  'the plane to Houston',
  'will some day be antique',
  'to connect and to divide',
  'the aid of the party',
  'your entire lifetime',
  'do not erase. Do not cross out. Do not strike',
  'Let your errors stand',
  'Finish every line you start',
  'you made errors',
  'strike the right keys',
  'require a lighter touch',
  'the even timing of a metronome',
  '"The Father of Our Country"',
  '"We\'ll meet at the theater," said the actress',
  'from London to Broadway',
  'the omission of',
  'possession as in "Mary\'s"',
  'JEANETTE KIMBALL',
  'THE COMPUTER SHOW THAT EVEN ADULTS CAN UNDERSTAND',
  'NEW YORK UNIVERSITY',
  'School of Law',
  'Annual Homecoming',
  'The Bridge of San Luis Rey',
  'Thornton Wilder',
  'THE ROYAL OPERA HOUSE, COVENT GARDEN',
  'LUCIA DI LAMMERMOOR',
  'Zelda quickly mixed the very big jar of new soap flakes',
  'For many people',
  'relaxation, recreation and restoration',
  'a liberation from routine',
  'a celebration of new visual and mental sensations',
  'rings to warn you',
  'you are approaching the end of a line',
  'space across your paper',
  'listen for the bell',
  'count the number of spaces beyond the bell',
  'You will soon respond to the bell automatically',
  'Now is the time for all good men',
  'improvement of the environment',
  'beautify our avenues',
  'this is not absolute',
  'flying to Florida in July made Sally decide to fly',
  'RESTIGOUCHE RIVER',
  'To Lease Luxury Office Space At',
  'A MAGNIFICENT NEW OFFICE BUILDING',
  'The EXCITEMENT of Computers',
  'The FUN of Camping',
  'Sessions for Teenagers',
  'Come to SHERATON',
  'Come to LUXURY',
  'Hotels, Inns & Resorts Worldwide',
  'DOWN COMFORTERS',
  'DOWN PILLOWS',
  'Save Half the Retail Price',
  'FACTORY DIRECT PRICES',
  'ADULT EDUCATION',
  'THE NEW SCHOOL',
  'REGISTER NOW',
  'the lyrics to a song',
  'do not neglect your daily work',
  'you must continue',
  'selling bath towels for $7.47',
  'Meet me at 7:47 p.m. at the airport on April 7',
  'going out of business',
  'fine wool suits',
  'SOPHISTICATED LADY',
  'hardly visible',
  'lawsuits are still pending',
  'What a hot day!',
  'What a surprise!',
  'All of the 15 guests are on time',
  'What a high price!',
  'Do this arithmetic',
  'The hospital',
  'Come early!',
  'What a beautiful painting!',
  'Who is the artist?',
  'Oh! I had no idea that this is your work',
  'surprise or strong emotion',
  'It\'s truly amazing!',
  'I don\'t believe it!',
  'You must leave immediately!',
  'last minute shopping',
  'Meet me at my office',
  '17 cases of canned fruit',
  'perfect condition',
  'The spring semester seems to pass much faster',
  'we had terrible weather',
  'the master painter',
  'wife, sister, and daughter',
  'of prime importance',
  'He thought he saw',
  'make the exchange',
  'fish by air',
  'a dash of pepper',
  'shoes and shawl',
  'for all your lifetime',
  'California Canned Peaches',
  'Campbell\'s Soup',
  'The clock struck twelve',
  'There was a knock on the door',
  'Zack plucked up courage',
  'open the door a crack',
  'the rock that struck the deck',
  'come in pairs',
  'American Airlines, Flight #321 (New York to Chicago)',
  'United Airlines, Flight #25 (New York to San Francisco)',
  'Flight #1 (Around the World)',
  'New York to Europe',
  'San Francisco to the Orient',
  'the Palace Hotel',
  'the doctor\'s chart',
  'AT THE MACHINE',
  'in Kentucky',
  'after his marriage',
  'a woman of exceptional intellect and character',
  'less than a year',
  'a voracious reader',
  'quinine and quiet',
  'the malaria patient',
  'He was quite sure',
  'fingernails are long',
  'With the wine',
  'to a *foreign* country',
  'an occasional error',
  'concentratoin is necessary',
  'the skill of proodreading',
  'it must be inbisible',
  'any leffers',
  'the date',
  'the complimentary close',
  'the name of the dictator',
  'a most exciting trip to Kenya',
  'animals saw us in our cages',
  'wild animals are vegetarians',
  'protective parents',
  'the most voracious of the birds',
  'if you wish',
  'rather severe',
  'near the park',
  'It must have a garden',
  'Obviously, we are disappointed',
  'before the heat sets in',
  'Are you traveling first class?',
  'an elaborate meal',
  'THE CITY OF NEW YORK',
  'Where? Why? How?',
  'Spring forward!',
  'Fall back!',
  'a competent office worker',
  'parliamentary procedure',
  'she sells jade flakes',
  'he sells old oak',
  'he has a salad',
  'The man and the dog did go to the lake',
  'The duck, the fox, and the fish make problems for the girl',
  'They may wish to blame me',
  'the fight to end the problem',
  'go to town for the pen',
  'the eighth of May',
  'load down rock jams',
  'Park my gray, bronze jet and quickly wax it for five hours',
  'helping Mr. Van',
  'The disc jockey',
  'pink gems and my quartz jewerly',
  'It is not the right time for us to talk about all the work',
  'cold, clear, and good to drink',
  'The light is dim',
  'it will give us all the light I need',
  'The bird floew way up in the sky to get away from the smoke',
  'See Ann at the doctor',
  'She has the food',
  'Dr. S. Romer called',
  'Rick loves that fame',
  'hear it hum',
  'Drive with a flair',
  'the clever quip of the journalist',
  'we will discuss her tax problems',
  'I\'m going to mow the lawn',
  'my sister can edge the lawn',
  'Summer is the zenith',
  'winter is quiet',
  'spanish leather goods',
  'now in reno',
  'science and art',
  'I can print it so fast',
  'The skirt is plaid',
  'her Ph.D. from Oregon State',
  'The U.S.A. and the U.S.S.R.',
  'so helpful',
  'Do you want to go to the movies?',
  'a Japanese import firm',
  'inadequate for our purposes',
  'the western part of Kalamazoo',
  'a former colonel in the Marines',
  'Zach, move that ax back into that cave',
  'I wanted to go to the shore today',
  'much too chilly',
  'Autumn in the "northlands" is very exciting',
  'in the early morning',
  'under a clear, azure blue',
  'the strong chill in the air',
  'The leaves have lost their brilliant green',
  'they have been tinted by someone passing by',
  'The truth is',
  'during the night hours',
  'a frost has painted the green to hues of brown',
  'yellow, red, and orange',
  'a breathtaking panorama in technicolor',
  'you\'ll not soon forget beauty such as this',
  'view the sights as you move along',
  'the man\'s woven zipper bag',
  'To watch teh quirrel is a good lesson, some say',
  'frozen jams with vigor',
  'she may take a walk',
  'many jovial men',
  'Al Juarez <u>does not</u> believe',
  'if you could just do as you wanted',
  'a dotted Swiss dress',
  'as old as cities or towns',
  'to the bluff beyond',
  'the zeal to take the extra list',
  'We cannot let him squander his time',
  'There is no equal to the flavor of ice cream',
  'hot, humid days',
  'a big smile',
  'a new friend',
  'those who join him there',
  'quiet jet streams of sunlight',
  'new and vital source of energy',
  'the lake was a huge sheet of silver',
  'When it began to rain',
  'it was BLUE-GREEN, not GRAY',
  'The clown from Quebec',
  'paint is a joy',
  'The zeal with which they work',
  'the bright hues take form',
  'smiles to our faces',
  'type, type, type',
  'six azure kites',
  'very huge maples',
  'a GREAT DEAL of MONEY',
  'Please let me know, Dr. Chen',
  'Six bright families',
  'a place to make a home',
  'The big tree has something to share with us all',
  'The goal of the rich girls',
  'greedy folks',
  'Getting up in the morning is quite a job',
  'go for the bus--just in time to miss it',
  'Next time I will not doze so long',
  'I can still make it',
  'the island with the oaks',
  'do not make any sound',
  'The women in a village',
  'new, warm quilts',
  'crazy quilts',
  'early Western life',
  'They <u>may</u>soon<u>know</u>how<u>good</u>they are',
  'We packed our clothes, food, and a tent',
  'cities, tall buildings, and busy offices',
  'she did so very well',
  'it got very windy',
  'Will my friends want to help?',
  'It <u>is</u> not <u>up</u> to <u>us</u>',
  'It is <u>not</u>',
  '<u>very, very well written</u>',
  'zestful lives',
  'Rush him eight bushels of corn',
  'We\'re so happy. Aren\'t you pleased?',
  'Look at the sky!',
  'You can see it from here! Wow!',
  'Japan and Turkey',
  'I did as he "offered"',
  'I went in',
  'I seemd "excited"',
  'he listened',
  '"What\'s your news?"',
  'Did he already "know"?',
  'Is it that we don\'t "care" and "feel"',
  'a joy to finish',
  'a hold on things',
  'those lucky persons',
  'Watch the beautiful eagle!',
  'Shout! Up! No! Down! There! Yes! Here! Oh!',
  '"Isn\'t it fine!"',
  'he won\'t speak',
  'he can\'t',
  '"It\'s <u>Oklahoma!</u>"',
  'a game of hues',
  'we prefer to go skiing',
  'from West Virgina to the West Coast',
  'special thoughts that you have for your friend',
  'does 2 + 2 = 4? Of course!',
  'the wind hits the leaves',
  'The new moon went over the hills and out of sight too soon',
  'for the lake and the land',
  'Look! What a fantastic sight!',
  'as wide as you wish',
  '<u>You</u> were the winner!"',
  'Go to a state park',
  'Eat at a country inn',
  'Camp overnight',
  'Go to Lake Aurora',
  'TAKE CLASSES IN BIKE SAFETY',
  'A HISTORY OF PARACHUTING',
  '<u>A History of Flying</u>',
  'driving a bus for a park zoo',
  'rapids that are fearsome to hear',
  'rocky, thorny, and hot in summer',
  'spray and sand hit you in the face',
  'a brisk and stinging jolt',
  'Join a Club',
  'Take Up a Sport',
  'the leaves start to fall in September',
  'fresh jam was quite lively',
  'Strong legs, quick reflexes',
  'skill--not size--is required',
  'from the Orient',
  'It is his fault',
  'Why must I leave?',
  'why not?',
  'Six crows in the blue sky'
];
